version: "3.8"
services:
  app:
    build: . # 로컬 소스로 이미지를 새로 빌드하라고 하는 것
    image: jeunju528/pinia-app:latest # 빌드한 이미지에 이름(태그)을 새로 붙이는 것
    container_name: pinia-app
    ports:
      - "9090:9090"
    env_file:
      - .env
    restart: always